package pl.jit.flashcards.service.impl;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.codec.digest.DigestUtils;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import pl.jit.flashcards.data.api_model.FlashcardSuggestionApiModel;
import pl.jit.flashcards.data.request.GenerateFlashcardsRequest;
import pl.jit.flashcards.data.response.GenerateFlashcardsResponse;
import pl.jit.flashcards.entity.GenerationEntity;
import pl.jit.flashcards.repository.GenerationRepository;
import pl.jit.flashcards.service.AiIntegrationService;
import pl.jit.flashcards.service.GenerationService;

import java.time.Instant;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class GenerationServiceImpl implements GenerationService {

    private static final int MAX_SOURCE_TEXT_LENGTH = 10000;

    private final AiIntegrationService aiIntegrationService;
    private final GenerationRepository generationRepository;

    @Override
    @Transactional
    public GenerateFlashcardsResponse generateFlashcards(GenerateFlashcardsRequest request) {
        validateSourceText(request.sourceText());

        long startTime = System.currentTimeMillis();
        List<FlashcardSuggestionApiModel> suggestions = aiIntegrationService.generateSuggestions(request.sourceText());
        long endTime = System.currentTimeMillis();
        long generationTimeMs = endTime - startTime;

        GenerationEntity generationEntity = createAndSaveGenerationRecord(request.sourceText(), generationTimeMs, suggestions.size());

        log.info("Generated {} flashcard suggestions in {} ms for generationId: {}",
                suggestions.size(), generationTimeMs, generationEntity.getId());

        return new GenerateFlashcardsResponse(
                generationEntity.getId(),
                generationEntity.getCreatedAt(),
                generationTimeMs,
                suggestions
        );
    }

    private void validateSourceText(String sourceText) {
        if (sourceText == null || sourceText.isBlank()) {
            throw new IllegalArgumentException("Source text cannot be empty.");
        }
        if (sourceText.length() > MAX_SOURCE_TEXT_LENGTH) {
            throw new IllegalArgumentException("Source text exceeds maximum length of " + MAX_SOURCE_TEXT_LENGTH + " characters.");
        }
    }

    private GenerationEntity createAndSaveGenerationRecord(String sourceText, long generationTimeMs, int suggestionCount) {
        GenerationEntity entity = new GenerationEntity();
        entity.setCreatedAt(Instant.now());
        entity.setSourceTextMd5(DigestUtils.md5Hex(sourceText));
        entity.setSourceTextLength(sourceText.length());
        entity.setGenerationTimeMs((int) generationTimeMs);
        entity.setSuggestedFlashcardsCount(suggestionCount);
        // ID is generated by the database
        return generationRepository.save(entity);
    }
}
